export const ferryFlowAbi = [
  {
    type: "event",
    name: "FlowConfigured",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "nonce", type: "uint256", indexed: true },
      { name: "destinations", type: "address[]", indexed: false },
      { name: "basisPoints", type: "uint256[]", indexed: false },
    ],
  },
  {
    type: "event",
    name: "FlowDisabled",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "nonce", type: "uint256", indexed: true },
    ],
  },
  {
    type: "event",
    name: "FlowExecuted",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "from", type: "address", indexed: true },
      { name: "value", type: "uint256", indexed: false },
      { name: "authorizationNonce", type: "bytes32", indexed: true },
      { name: "destinationCount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "FlowDistribution",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "authorizationNonce", type: "bytes32", indexed: true },
      { name: "destination", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "destinationIndex", type: "uint256", indexed: false },
    ],
  },
  {
    type: "function",
    name: "configurationNonces",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getFlow",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [
      { name: "destinations", type: "address[]" },
      { name: "basisPoints", type: "uint256[]" },
    ],
  },
  {
    type: "function",
    name: "configureFlow",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "destinations", type: "address[]" },
      { name: "basisPoints", type: "uint256[]" },
      { name: "nonce", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "v", type: "uint8" },
      { name: "r", type: "bytes32" },
      { name: "s", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "executeFlow",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "from", type: "address" },
      { name: "value", type: "uint256" },
      { name: "validAfter", type: "uint256" },
      { name: "validBefore", type: "uint256" },
      { name: "authNonce", type: "bytes32" },
      { name: "v", type: "uint8" },
      { name: "r", type: "bytes32" },
      { name: "s", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "disableFlow",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "nonce", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "v", type: "uint8" },
      { name: "r", type: "bytes32" },
      { name: "s", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "error",
    name: "InvalidConfigurationNonce",
    inputs: [
      { name: "expected", type: "uint256" },
      { name: "provided", type: "uint256" },
    ],
  },
  { type: "error", name: "SignatureExpired", inputs: [] },
  { type: "error", name: "InvalidSignature", inputs: [] },
  { type: "error", name: "AuthorizationOwnerMismatch", inputs: [] },
  { type: "error", name: "InvalidDestinationCount", inputs: [] },
  { type: "error", name: "ArrayLengthMismatch", inputs: [] },
  { type: "error", name: "ZeroBasisPoints", inputs: [] },
  { type: "error", name: "InvalidBasisPointTotal", inputs: [] },
  { type: "error", name: "DuplicateDestination", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "ZeroValue", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
] as const;
